### ISSUE TITLE
Shared IP address provokes collision on validator nodes

### ISSUE THREAD

**Issue by miloskriz** [Cardinal-Cryptography/aleph-node#752]
Dear team:

Please consider the following **use case**: using one machine with validator intent in both testnet and mainnet chains, let's please assume the bare metal specifications are over-dimensioned to allow plenty resources for both nodes. and. being both from different chains, this case should not affect the decentralisation of each individual chain.

**Problem**: at the moment, an error message is triggered when running a second `--validator` node using the same IPv4 address and different ports in the `--validator-port` flag:

```
 ====================
 Version: 0.8.0-a433672835f
    0: sp_panic_handler::set::{{closure}}
    1: std::panicking::rust_panic_with_hook
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:702:17
    2: std::panicking::begin_panic_handler::{{closure}}
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:588:13
    3: std::sys_common::backtrace::__rust_end_short_backtrace
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys_common/backtrace.rs:138:18
    4: rust_begin_unwind
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/panicking.rs:584:5
    5: core::panicking::panic_fmt
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/panicking.rs:142:14
    6: core::result::unwrap_failed
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/core/src/result.rs:1814:5
    7: finality_aleph::nodes::validator_node::run_validator_node::{{closure}}
    8: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
    9: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
   10: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   11: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   12: std::thread::local::LocalKey<T>::with
   13: tokio::park::thread::CachedParkThread::block_on
   14: tokio::runtime::handle::Handle::block_on
   15: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
   16: tokio::runtime::task::harness::Harness<T,S>::poll
   17: tokio::runtime::blocking::pool::Inner::run
   18: std::sys_common::backtrace::__rust_begin_short_backtrace
   19: core::ops::function::FnOnce::call_once{{vtable.shim}}
   20: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/alloc/src/boxed.rs:1935:9
       std::sys::unix::thread::Thread::new::thread_start
              at rustc/20ffea6938b5839c390252e07940b99e3b6a889a/library/std/src/sys/unix/thread.rs:108:17
   21: <unknown>
   22: <unknown>
 Thread 'tokio-runtime-worker' panicked at 'we should have working networking: Os { code: 98, kind: AddrInUse, message: "Address already in use" }', /home/user/aleph-node/finality-aleph/src/nodes/validator_node.rs:75
 This is a bug. Please report it at:
         docs.alephzero.org
```

The relevant flags of the first node are:
```
  --validator \
  --name <SOME_NAME> \
  --base-path '/var/lib/aleph-node/azero1' \
  --chain /var/lib/aleph-node/azero1/chainspec.json \
  --node-key-file /var/lib/aleph-node/azero1/p2p_secret \
  --backup-path /var/lib/aleph-node/azero1/backup-stash \
  --public-validator-addresses <SOME IP>:30345 \
  --port 30335 \
  --rpc-port 9935 \
  --ws-port 9946 \
  --prometheus-port 9617 \
  --database rocksdb \
  --state-pruning archive \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 1' \
  --bootnodes <REDACTED> \
  --wasm-execution Compiled --execution native-else-wasm --pool-limit 100 --unit-creation-delay 300 --enable-log-reloading
```

and the second node has:
```
  --validator \
  --name SOME_OTHER_NODE \
  --base-path '/var/lib/aleph-node/tzero1' \
  --chain /var/lib/aleph-node/tzero1/chainspec.json \
  --node-key-file /var/lib/aleph-node/tzero1/p2p_secret \
  --backup-path /var/lib/aleph-node/tzero1/backup-stash \
  --public-validator-addresses <SAME IP>:30346 \
  --port 30336 \
  --rpc-port 9936 \
  --ws-port 9947 \
  --prometheus-port 9618 \
  --database rocksdb \
  --state-pruning archive \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 1' \
  --bootnodes <REDACTED> \
  --wasm-execution Compiled --execution native-else-wasm --pool-limit 100 --unit-creation-delay 300 --enable-log-reloading
```

Please advise in case you require more details to reproduce this behaviour.

Many thanks!!

**_Milos_**

**Comment by miloskriz** [comment]
just an additional note:

- When both `--validator` flags are removed, the nodes work perfectly well together.
- When one `--validator` flag is active in one node, the other node can coexist without the validator intent.
- When both `--validator` flags are added, the second node to start results in the error reproduced above.

hope it helps!

Cheers :-)

**Comment by timorl** [comment]
You seem to be missing the `--validator-port` argument – `--public-validator-addresses` is only for the _externally accessible_ address, which might be completely different than the one you locally listen on, so we cannot infer from it the port you want to listen on and you unfortunately have to provide it twice. If the port you locally listen on is the exact same as in the address, simply add `--validator-port 30345` to the first argument list and `--validator-port 30346` to the second.

The panic is due to one of the nodes reserving the default (30343) port first and the second one attempting to also use it. Note that even if you were running just one node, it would be incorrectly configured, as it would listen on `30343`, while advertising its address at `3034[56]` – you always have to provide the `--validator-port` argument when you want to use a different port.

I hope this helps. ^^

**Comment by miloskriz** [comment]
dear @timorl,

Many thanks for finding the issue!!... I can confirm this is working now...

Have a great day!!! :-D

Milos
